---
# This workflow integrates Qwiet.AI with GitHub
# Visit https://docs.shiftleft.io for help
name: Qwiet AI

on:
  pull_request:
  workflow_dispatch:

jobs:
  preZero:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: QwietAI/qwiet-action@main
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        CPG_EXPORT: true
    - name: Upload cpg
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cpg
        path: cpg_out
    - name: Upload graph
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cpg_exports
        path: cpg_export
